# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/jlee167/OKPipes/lab7pipeInPipeOut/lab4_pt01.srcs/sources_1/new/xem7310.xdc

# IP: ip/ila/ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila}]

# XDC: C:/Users/jlee167/OKPipes/lab7pipeInPipeOut/lab4_pt01.srcs/i2c_core/new/i2c_core_ooc.xdc

# XDC: C:/Users/jlee167/OKPipes/lab7pipeInPipeOut/lab4_pt01.srcs/i2c_driver/new/i2c_driver_ooc.xdc

# XDC: C:/Users/jlee167/OKPipes/lab7pipeInPipeOut/lab4_pt01.srcs/clkDivCustom24bit/new/clkDivCustom24bit_ooc.xdc

# XDC: C:/Users/jlee167/OKPipes/lab7pipeInPipeOut/lab4_pt01.srcs/concat_1to4_withAddr/new/concat_1to4_withAddr_ooc.xdc

# XDC: C:/Users/jlee167/OKPipes/lab7pipeInPipeOut/lab4_pt01.srcs/mux4to1_withAddr/new/mux4to1_withAddr_ooc.xdc

# XDC: ip/ila/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila}] {/inst }]/inst ]]

# XDC: ip/ila/ila_ooc.xdc
